<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>task_priority_kinematic_control_rqt</name>
  <version>0.1.0</version>
  <description>RQT plugin for task priority kinematic control.</description>

  <maintainer email="barajas@uji.es">usuario</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>python_qt_binding</depend>
  <depend>rqt_gui</depend>
  <depend>rqt_gui_py</depend>
  <depend>geometry_msgs</depend>
  <depend>std_srvs</depend>
  <depend>task_priority_kinematic_control</depend>

  <export>
    <build_type>ament_python</build_type>
    <rqt_gui plugin="${prefix}/plugin.xml"/>
  </export>
</package>
